// components/Footer.vue
<template>
    <div>
        <footer>
            <div id="primeiro" class="p-4 text-center bg-[var(--cor-Principal)] border-t-[1px] border-white/30 mt-4">
                <p class="text-white">
                    Desenvolvido por 
                    <NuxtLink
                        href="https://github.com/RosiestSloth"
                        target="_blank" 
                        rel="noopener" 
                        class="duration-100 ease hover:text-white/70"
                    >
                        Vinicius
                    </NuxtLink>
                    | &copy; Todos os direitos reservados
                </p>
            </div>
            <div id="segundo" class="bg-[var(--cor-Principal)] p-4 flex flex-col justify-center items-center sm:relative w-full h-28 border-t border-white/40">
                <div id="titulo" class="absolute left-4 hidden sm:block">
                    <h1 id="titulo_footer" class="text-white">
                        Vinicius
                    </h1>
                </div>
                <div id="links" class="sm:absolute sm:transform sm:-translate-x-1/2 sm:-translate-y-1/2 sm:top-1/2 sm:left-1/2 flex gap-2">
                    <NuxtLink 
                    class="hover:text-white duration-100 ease bg-white/50 hover:bg-white/30 p-1 rounded-sm border-1 border-white/80 hover:border-white/30" 
                    to="/About"
                    id="button"
                    aria-label="Página de Sobre Mim"
                    >
                        Sobre mim
                    </NuxtLink>
                    <NuxtLink
                    class="hover:text-white duration-100 ease bg-white/50 hover:bg-white/30 p-1 rounded-sm border-1 border-white/80 hover:border-white/30"
                    to="/Works"
                    id="button"
                    aria-label="Página de Meus Trabalhos"
                    >
                        Meus Trabalhos
                    </NuxtLink>
                </div>

                <nav id="redes" class="flex sm:absolute sm:right-4 sm:gap-0 md:gap-2">
                    <NuxtLink
                        href="https://www.tiktok.com/@vinicius___santos329?lang=pt-BR"
                        target="_blank"
                        rel="noopener"
                        aria-label="Meu TikTok"
                    >
                        <TikTokIcon
                        class="transform hover:-scale-[1.1] size-10 p-1 duration-100 ease hover:bg-black/20 rounded-md"
                        />
                    </NuxtLink>
                    <NuxtLink
                        href="https://api.whatsapp.com/send/?phone=%2B5562992846807&text&type=phone_number&app_absent=0"
                        target="_blank" 
                        rel="noopener"
                        aria-label="Meu Whatsapp"
                    >
                    <WhatsappIcon 
                        class="transform hover:-scale-[1.1] size-10 p-1 duration-100 ease hover:bg-black/20 rounded-md"
                        />
                    </NuxtLink>
                    <NuxtLink
                        href="https://www.instagram.com/vinicius___santos1?igsh=cHlrMGN0cWthZXAy&utm_source=qr"
                        target="_blank" 
                        rel="noopener"
                    >
                    <InstagramIcon 
                        class="transform hover:-scale-[1.1] size-10 p-1 duration-100 ease hover:bg-black/20 rounded-md"
                        />
                    </NuxtLink>
                    <NuxtLink
                        href="https://github.com/RosiestSloth" target="_blank" 
                        rel="noopener"
                    >
                    <GithubIcon 
                        class="transform hover:-scale-[1.1] size-10 p-1 duration-100 ease hover:bg-black/20 rounded-md"
                    />
                    </NuxtLink>
                </nav>
            </div>
        </footer>
    </div>
</template>

<script setup>
    import GithubIcon from '../public/svgs/GitHub.svg';
    import InstagramIcon from '../public/svgs/Instagram.svg';
    import TikTokIcon from '../public/svgs/TikTok.svg';
    import WhatsappIcon from '../public/svgs/WhatsApp.svg';
</script>

// src/components/shared/Footer.jsx
import { Link } from 'react-router-dom';

function Footer() {
  const navLinks = [
    { to: '/', label: 'Home' },
    { to: '/about', label: 'Sobre' },
    { to: '/works', label: 'Trabalhos' },
    { to: '/services', label: 'Serviços' },
    { to: '/gallery', label: 'Galeria' },
    { to: '/contact', label: 'Contato' },
  ];

  return (
    <footer className="">
      {/* Primeira seção do footer */}
      <div className="text-white font-body text-md bg-(--primary-color) px-6 md:px-10 lg:px-20 py-8 md:py-12">
        <p>
          “Transformando ideias em experiências digitais excepcionais através de
          código limpo, design intuitivo e foco em resultados. Vamos construir o
          futuro da web juntos.”
        </p>
      </div>
      {/* Conteúdo principal do footer */}
      <div className="bg-(--tertiary-color) border-t border-gray-100 px-6 md:px-10 lg:px-20 py-8 md:py-12">
        <div className="flex flex-col md:flex-row items-start justify-around gap-10">
          <div className="flex-1">
            <img
              src="/img/Logo White.png"
              alt="Logo White"
              className="w-40 rounded-xl"
            />
            <p className="font-body text-gray-100 mt-4">
              Desenvolvedor Full Stack apaixonado por criar experiências
              digitais incríveis.
            </p>
          </div>
          <div className="flex-1">
            <h2 className="font-heading font-bold text-white text-2xl">
              Links Rápidos
            </h2>
            <ul className="font-body mt-4 flex flex-col gap-2">
              {/* Links Rápidos */}
              {navLinks.map((link) => {
                return (
                  <li key={link.to}>
                    <Link
                      to={link.to}
                      className="text-gray-50 hover:text-gray-300"
                    >
                      {link.label}
                    </Link>
                  </li>
                );
              })}
            </ul>
          </div>
          <div className="flex-1">
            <h2 className="font-heading font-bold text-white text-2xl">
              Minhas Redes
            </h2>
            <ul className="font-body mt-4 flex gap-4">
              <li className="hover:scale-105 hover:bg-gray-50/20 p-2 rounded-md transition duration-100">
                <a
                  target="_blank"
                  href="https://github.com/RosiestSloth"
                  rel="noopener"
                >
                  <img src="svg/GitHub.svg" alt="" />
                </a>
              </li>
              <li className="hover:scale-105 hover:bg-gray-50/20 p-2 rounded-md transition duration-100">
                <a
                  target="_blank"
                  href="https://instagram.com/vinicius___santos1"
                  rel="noopener"
                >
                  <img src="svg/Instagram.svg" alt="" />
                </a>
              </li>
              <li className="hover:scale-105 hover:bg-gray-50/20 p-2 rounded-md transition duration-100">
                <a
                  target="_blank"
                  href="https://wa.me/5562992846807"
                  rel="noopener"
                >
                  <img src="svg/WhatsApp.svg" alt="" />
                </a>
              </li>
              <li className="hover:scale-105 hover:bg-gray-50/20 p-2 rounded-md transition duration-100">
                <a
                  target="_blank"
                  href="https://linkedin.com/in/rosiestsloth"
                  rel="noopener"
                >
                  <img src="svg/LinkedIn.svg" alt="" />
                </a>
              </li>
            </ul>
          </div>
        </div>
        {/* Direitos Autorais */}
        <p className="text-center text-gray-300 border-t border-t-gray pt-10 mt-10">
          © 2026 Vinicius Santos. Todos os direitos reservados.
        </p>
      </div>
    </footer>
  );
}

export default Footer;
