// components/Header.vue
<template>
    <header class="p-8 bg-[var(--cor-Principal)]">
        <div class="flex items-center relative h-10">
            <h1 class="hidden lg:block text-white absolute left-2">
                Vinicius
            </h1>
            <nav aria-label="Navegação Desktop" class="flex items-center justify-between w-full max-w-xl h-12 rounded-md mx-auto bg-[var(--conteiners)] absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
                <NuxtLink
                    aria-label="Navegação para o Início"
                    class="group flex items-center font-chamadas gap-2 hover:text-white duration-100 ease-in w-full hover:bg-[var(--hover)] h-12 rounded-l-md pl-2"
                    to="/"
                    id="button"
                    :class="{ 'active': isHomeActive }"
                    @click="setActiveLink('home')"
                    >
                    <HomeIcon id="icon-home"
                        class="sm:block hidden stroke-black fill-black/20 group-hover:stroke-white group-hover:fill-white/20 size-8 duration-100 ease-in"
                    />
                    <p class="w-full text-center sm:w-auto">Home</p>
                </NuxtLink>
                <NuxtLink
                    aria-label="Navegação para a página Sobre mim"
                    class="group flex items-center gap-2 hover:text-white text-center duration-100 ease-in w-full hover:bg-[var(--hover)] h-12 before:w-[1px] before:h-[40px] before:bg-black/50"
                    to="/About"
                    id="button"
                    :class="{ 'active': isAboutActive }"
                    @click="setActiveLink('about')"
                    >
                    <AboutIcon id="icon" class="sm:block hidden stroke-black fill-black group-hover:stroke-white group-hover:fill-white size-8 duration-100 ease-in"/>
                    <p class="w-full text-center sm:w-auto">Sobre</p>
                </NuxtLink>
                <NuxtLink
                    aria-label="Navegação para a página Meus Trabalhos"
                    class="group flex items-center gap-2 hover:text-white duration-100 ease-in w-full hover:bg-[var(--hover)] h-12 before:w-[1px] before:h-[40px] before:bg-black/50 pr-2"
                    to="/Works"
                    id="button"
                    :class="{ 'active': isWorksActive }"
                    @click="setActiveLink('works')"
                    >
                    <WorksIcon id="icon" class="sm:block hidden stroke-black fill-black group-hover:stroke-white group-hover:fill-white size-8 duration-100 ease-in"/>
                    <p class="w-full text-center sm:w-auto">Trabalhos</p>
                </NuxtLink>
                <NuxtLink
                    aria-label="Navegação para a página Minhas Fotos"
                    class="group flex items-center gap-2 hover:text-white duration-100 ease-in w-full ml-[-1px] hover:bg-[var(--hover)] h-12 rounded-r-md before:w-[1px] before:h-[40px] before:bg-black/50"
                    to="/Photos"
                    id="button"
                    :class="{ 'active': isPhotosActive }"
                    @click="setActiveLink('photos')"
                    >
                    <PhotosIcon id="icon" class="sm:block hidden stroke-black fill-black group-hover:stroke-white group-hover:fill-white size-8 duration-100 ease-in"/>
                    <p class="w-full text-center sm:w-auto">Fotos</p>
                </NuxtLink>
            </nav>
        </div>
    </header>
</template>

<script setup>
    import HomeIcon from '../public/svgs/Home.svg';
    import AboutIcon from '../public/svgs/About.svg';
    import WorksIcon from '../public/svgs/Works.svg';
    import PhotosIcon from '../public/svgs/Photos.svg';
    import { ref, onMounted, computed } from 'vue'
    import { useRoute } from 'vue-router'

    const route = useRoute()
    
    const isHomeActive = ref(false)
    const isAboutActive = ref(false)
    const isWorksActive = ref(false)
    const isPhotosActive = ref(false)

    const setActiveLink = (link) => {
        isHomeActive.value = link === 'home'
        isAboutActive.value = link === 'about'
        isWorksActive.value = link === 'works'
        isPhotosActive.value = link === 'photos'
    }

    onMounted(() => {
        const path = route.path
        if (path === '/') setActiveLink('home')
        else if (path === '/About') setActiveLink('about')
        else if (path === '/Works') setActiveLink('works')
        else if (path === '/Photos') setActiveLink('photos')
    })

    const backgroundClass = computed(() => {
        switch (route.path) {
            case '/':
                return 'bg-home'
            case '/About':
                return 'bg-about'
            case '/Works':
                return 'bg-works'
            case '/Photos':
                return 'bg-photos'
            default:
                return 'bg-default'
        }
    })
</script>

<style scoped>
    .active {
        background-color: var(--hover);
        color: white;
        pointer-events: none;
    }

    .active #icon {
        stroke: white;
        fill: white;
    }

    .active #icon-home {
        stroke: white;
        fill: rgba(255, 255, 255, 0.200);
    }
</style>

// src/components/shared/Header.jsx
import { Link } from "react-router-dom";
import { useState, useEffect } from "react";

function Header() {
    const [isScrolled, setIsScrolled] = useState(false);
    const [menuOpen, setMenuOpen] = useState(false);

    useEffect(() => {
        const handleScroll = () => {
            setIsScrolled(window.scrollY > 50);
        };
        window.addEventListener('scroll', handleScroll);
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);

    const navLinks = [
        { to: "/", label: "Home" },
        { to: "/pages/About", label: "Sobre" },
        { to: "/pages/Works", label: "Trabalhos" },
        { to: "/pages/Services", label: "Serviços" },
        { to: "/pages/Gallery", label: "Galeria" },
        { to: "/pages/Contact", label: "Contato" },
    ];

    return (
        <>
            {/* Botão hambúrguer */}
            <button
                onClick={() => setMenuOpen(!menuOpen)}
                className="lg:hidden fixed top-4 right-4 z-100 w-12 h-12 flex flex-col items-center justify-center gap-1.5 bg-gray-100/70 backdrop-blur-sm rounded-full shadow-md border border-gray-300 cursor-pointer"
                aria-label="Toggle menu"
            >
                <span className={`block w-5 h-0.5 bg-gray-800 transition-all duration-300 ${menuOpen ? 'rotate-45 translate-y-2' : ''}`} />
                <span className={`block w-5 h-0.5 bg-gray-800 transition-all duration-300 ${menuOpen ? 'opacity-0' : ''}`} />
                <span className={`block w-5 h-0.5 bg-gray-800 transition-all duration-300 ${menuOpen ? '-rotate-45 -translate-y-2' : ''}`} />
            </button>
    
            {/* Overlay */}
            {menuOpen && (
                <div
                    className="lg:hidden pointer-events-none fixed inset-0 bg-black/40 z-40 backdrop-blur-sm"
                    onClick={() => setMenuOpen(false)}
                />
            )}
    
            {/* Drawer MOBILE */}
            <aside className={`
                lg:hidden fixed z-50 top-0 right-0 h-full w-64 p-6
                flex flex-col justify-center
                bg-gray-100/70 backdrop-blur-sm shadow-md border-l border-gray-300
                transition-transform duration-300
                ${menuOpen ? 'translate-x-0' : 'translate-x-full'}
            `}>
                <nav>
                    <ul className="flex flex-col gap-2 font-medium text-lg">
                        {navLinks.map(({ to, label }) => (
                            <li key={to}>
                                <Link to={to} className="w-full rounded-full h-14 flex items-center justify-center text-(--tertiary-color) hover:bg-gray-800/20 transition-colors duration-100 cursor-pointer" onClick={() => setMenuOpen(false)}>{label}</Link>
                            </li>
                        ))}
                    </ul>
                </nav>
            </aside>
    
            {/* Header DESKTOP — pill centralizada */}
            <header className={`
                hidden lg:flex fixed z-50
                flex-row items-center justify-center
                bg-gray-100/70 backdrop-blur-sm shadow-md border border-gray-300
                rounded-full p-2
                left-1/2 -translate-x-1/2
                transition-all duration-300
                ${isScrolled ? 'top-8' : 'top-4'}
            `}>
                <nav>
                    <ul className="flex flex-row items-center justify-center gap-2 font-medium text-lg">
                        {navLinks.map(({ to, label }) => (
                            <li key={to}>
                                <Link className="w-30 rounded-full h-14 flex items-center justify-center hover:bg-gray-800/20 text-(--tertiary-color) transition-colors duration-100 cursor-pointer" to={to}>{label}</Link>
                            </li>
                        ))}
                        <li>
                            <div className="relative w-14 hover:w-35 transition-all cursor-pointer h-14 overflow-hidden rounded-full bg-white border border-gray-200">
                                <img src="/img/Logo White.png" className="size-full absolute object-cover object-left top-1/2 -translate-y-1/2 left-1/2 -translate-x-1/2" alt="" />
                            </div>
                        </li>
                    </ul>
                </nav>
            </header>
        </>
    );
}

export default Header;
